# Aphrodite — CCR compression proxy for Hermes Agent.
#
# Single systemd-managed proxy instance backed by the upstream
# aphrodite-x86_64-unknown-linux-gnu binary. Listens on 127.0.0.1
# only by default (loopback is mandatory: the upstream /retrieve,
# /ccr/*, /history endpoints have no auth of their own, so the
# router already rejects non-loopback callers but binding 0.0.0.0
# still exposes them on loopback-equivalent interfaces).
#
# One proxy == one upstream provider (api_url + api_key) and one
# CCR backend (cache in-memory vs token SQLite). Different
# provider/model combos from the same upstream can share a single
# proxy because aphrodite forwards payload.model verbatim, so
# MiniMax-M3 and MiniMax-M2.7 both route through the same unit
# with the same API key.
#
# Config file is rendered at /etc/aphrodite/aphrodite.toml by the
# preStart script so the upstream config-file watcher (which
# auto-reloads on mtime change) sees it. APHRODITE_CONFIG_PATH
# is exported in the unit to override the default search path
# (~/.hermes/aphrodite/aphrodite.toml) which the hermes user
# doesn't own.
#
# The user_key for the proxy lives in sops at
#   /run/secrets/aphrodite/MINIMAX_API_KEY
# which is declared as a service-specific secret in
# hosts/aleroza-pc/default.nix. The preStart script reads it as
# root and bakes the value into the rendered TOML.

{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.aphrodite;
  autoCfg = config.auto.aphrodite;

  # Upstream binary — pinned to Aphrodite/v1.3.8 (x86_64-linux).
  # sha256 verified against the upstream SHA256SUMS file at
  # https://github.com/PlayForm/Aphrodite/releases/download/Aphrodite/v1.3.8/SHA256SUMS-x86_64-unknown-linux-gnu.txt
  aphroditeBin = pkgs.fetchurl {
    url = "https://github.com/PlayForm/Aphrodite/releases/download/Aphrodite/v1.3.8/aphrodite-x86_64-unknown-linux-gnu";
    sha256 = "b2f3d71536c7291263b542bed5ff90b6d9271b4b2552369df5c3707e992caa18";
  };

  # TOML config rendered into the Nix store. Written to
  # /etc/aphrodite/aphrodite.toml by preStart on every activation.
  aphroditeConfig = pkgs.writeText "aphrodite.toml" ''
    # Generated by modules/services/aphrodite.nix — do not edit.
    # Re-run nixos-rebuild switch to regenerate.

    [[proxies]]
    name = "${cfg.proxyName}"
    listen = "${cfg.listen}"
    api_key_env = "${cfg.apiKeyEnv}"
    mode = "${cfg.mode}"
    tool_relay = ${if cfg.toolRelay then "true" else "false"}
    timeout = ${toString cfg.timeout}

    [defaults]
    api_url = "${cfg.apiUrl}"
    model = "${cfg.defaultModel}"
    ccr_ttl_seconds = ${toString cfg.ccrTtlSeconds}

    [compression]
    engine_threshold_pct = ${toString cfg.compression.engineThresholdPct}
    engine_protect_first = ${toString cfg.compression.engineProtectFirst}
    engine_protect_last = ${toString cfg.compression.engineProtectLast}
    engine_min_msgs = ${toString cfg.compression.engineMinMsgs}
    tool_threshold_token = ${toString cfg.compression.toolThresholdToken}
    tool_threshold_cache = ${toString cfg.compression.toolThresholdCache}
    terminal_threshold = ${toString cfg.compression.terminalThreshold}
    inline_threshold = ${toString cfg.compression.inlineThreshold}
    auto_expand = ${if cfg.compression.autoExpand then "true" else "false"}
    auto_expand_limit = ${toString cfg.compression.autoExpandLimit}
    catalog_mode = "${cfg.compression.catalogMode}"
    classifier_poll = ${if cfg.compression.classifierPoll then "true" else "false"}
    code_multiplier = ${lib.toJSON cfg.compression.codeMultiplier}
    context_engine = ${if cfg.compression.contextEngine then "true" else "false"}
    prefetch = ${if cfg.compression.prefetch then "true" else "false"}

    [previews]
    model_family = "${cfg.previews.modelFamily}"
    code_structure_map = ${if cfg.previews.codeStructureMap then "true" else "false"}
    preview_max_chars = ${toString cfg.previews.previewMaxChars}

    [prompts]
    retrieve_guidance = "${cfg.prompts.retrieveGuidance}"
    ccr_marker_hint = ${if cfg.prompts.ccrMarkerHint then "true" else "false"}
    catalog_intent_hints = ${if cfg.prompts.catalogIntentHints then "true" else "false"}
  '';

  # PreStart renders /run/aphrodite/aphrodite.toml AND materialises
  # the upstream API key directly in the TOML's [defaults].api_key
  # field. The preStart runs as root before the unit drops to
  # User=aphrodite, so it has read access to the sops-managed
  # /run/secrets/aphrodite/MINIMAX_API_KEY (mode 0440 root:aphrodite).
  # This mirrors the pattern services/openviking.nix uses for
  # vlm.api_key, which is also baked into ov.conf via preStart.
  #
  # Nix `''` string body acts like a bash heredoc with both layers
  # of substitution active:
  #   - ${cfg.X}     — Nix interpolates at eval time, bash sees the
  #                    value as a literal (e.g. "token", 300, "true").
  #   - ''${VAR}     — Nix leaves the string literal, bash interpolates
  #                    at runtime from the local env.
  #   - "           — literal double-quote inside `''`; Nix does NOT
  #                    re-open a string here. Inside the bash heredoc
  #                    body it's a TOML string quote.
  preStartScript = pkgs.writeShellScript "aphrodite-pre-start" ''
    set -euo pipefail

    KEY_FILE=${cfg.apiKeyFile}
    if [[ ! -f "$KEY_FILE" ]]; then
      echo "aphrodite-pre-start: API key file not found: $KEY_FILE" >&2
      exit 1
    fi
    API_KEY=$(tr -d '\n' < "$KEY_FILE")
    if [[ -z "$API_KEY" ]]; then
      echo "aphrodite-pre-start: empty API key in $KEY_FILE" >&2
      exit 1
    fi

    CONF=/run/aphrodite/aphrodite.toml
    cat > "$CONF" <<TOML_EOF
    [[proxies]]
    name = "${cfg.proxyName}"
    listen = "${cfg.listen}"
    mode = "${cfg.mode}"
    tool_relay = ${if cfg.toolRelay then "true" else "false"}
    timeout = ${toString cfg.timeout}

    [defaults]
    api_url = "${cfg.apiUrl}"
    model = "${cfg.defaultModel}"
    api_key = "$API_KEY"
    ccr_ttl_seconds = ${toString cfg.ccrTtlSeconds}

    [compression]
    engine_threshold_pct = ${toString cfg.compression.engineThresholdPct}
    engine_protect_first = ${toString cfg.compression.engineProtectFirst}
    engine_protect_last = ${toString cfg.compression.engineProtectLast}
    engine_min_msgs = ${toString cfg.compression.engineMinMsgs}
    tool_threshold_token = ${toString cfg.compression.toolThresholdToken}
    tool_threshold_cache = ${toString cfg.compression.toolThresholdCache}
    terminal_threshold = ${toString cfg.compression.terminalThreshold}
    inline_threshold = ${toString cfg.compression.inlineThreshold}
    auto_expand = ${if cfg.compression.autoExpand then "true" else "false"}
    auto_expand_limit = ${toString cfg.compression.autoExpandLimit}
    catalog_mode = "${cfg.compression.catalogMode}"
    classifier_poll = ${if cfg.compression.classifierPoll then "true" else "false"}
    code_multiplier = ${lib.toJSON cfg.compression.codeMultiplier}
    context_engine = ${if cfg.compression.contextEngine then "true" else "false"}
    prefetch = ${if cfg.compression.prefetch then "true" else "false"}

    [previews]
    model_family = "${cfg.previews.modelFamily}"
    code_structure_map = ${if cfg.previews.codeStructureMap then "true" else "false"}
    preview_max_chars = ${toString cfg.previews.previewMaxChars}

    [prompts]
    retrieve_guidance = "${cfg.prompts.retrieveGuidance}"
    ccr_marker_hint = ${if cfg.prompts.ccrMarkerHint then "true" else "false"}
    catalog_intent_hints = ${if cfg.prompts.catalogIntentHints then "true" else "false"}
TOML_EOF

    chmod 0640 "$CONF"
    chown aphrodite:aphrodite "$CONF"

    echo "aphrodite-pre-start: wrote $CONF (key length=''${#API_KEY})"
  '';
in
{
  options.services.aphrodite = {
    enable = lib.mkEnableOption "Aphrodite CCR compression proxy for Hermes Agent";

    apiUrl = lib.mkOption {
      type = lib.types.str;
      default = "https://api.minimax.io";
      description = ''
        Upstream OpenAI-compatible API base URL. Aphrodite forwards
        payload.model verbatim, so any model served by the same
        api_url+api_key works through one proxy instance.
      '';
    };

    defaultModel = lib.mkOption {
      type = lib.types.str;
      default = "MiniMax-M3";
      description = "Default model forwarded when a request omits one.";
    };

    apiKeyEnv = lib.mkOption {
      type = lib.types.str;
      default = "MINIMAX_API_KEY";
      description = ''
        Name of the env var the proxy would read for the upstream
        bearer if no api_key was set in the TOML. The preStart
        materialises the key directly into the TOML's api_key
        field, so this option is informational — kept for parity
        with the upstream config schema.
      '';
    };

    apiKeyFile = lib.mkOption {
      type = lib.types.path;
      default = "/run/secrets/aphrodite/MINIMAX_API_KEY";
      description = ''
        Path to a file containing a bare API key (single line, no
        KEY= prefix). Read by ExecStartPre as root before the unit
        drops to User=aphrodite; the value is materialised into the
        rendered TOML's api_key field. Default reuses the
        service-specific sops secret declared by
        hosts/aleroza-pc/default.nix.
      '';
    };

    listen = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:9798";
      description = ''
        Loopback bind for the proxy. Loopback-only is mandatory —
        upstream /retrieve and /ccr/* have no auth of their own.
        Set to "0.0.0.0:9798" only if you deliberately want other
        machines to reach this proxy and understand the security
        trade-off.
      '';
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Open the firewall on services.aphrodite.listen's port. Only
        meaningful when listen is 0.0.0.0; ignored for loopback binds.
      '';
    };

    proxyName = lib.mkOption {
      type = lib.types.str;
      default = "token";
      description = ''
        Internal name for the proxy listener. The upstream uses
        "cache" and "token" as canonical names but accepts any
        string; "token" selects SQLite CCR backend by default.
      '';
    };

    mode = lib.mkOption {
      type = lib.types.enum [ "cache" "token" ];
      default = "token";
      description = ''
        CCR backend mode. "cache" = in-memory, threshold 8KB,
        ephemeral. "token" = SQLite, threshold 1KB, persistent.
        token is required for tool_relay across restarts.
      '';
    };

    toolRelay = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Forward tool-calling protocol through the proxy. Disable
        only for non-chat-completions endpoints.
      '';
    };

    timeout = lib.mkOption {
      type = lib.types.int;
      default = 300;
      description = "Upstream request timeout in seconds.";
    };

    ccrTtlSeconds = lib.mkOption {
      type = lib.types.int;
      default = 3600;
      description = "How long CCR entries live in the SQLite store.";
    };

    compression = {
      engineThresholdPct = lib.mkOption {
        type = lib.types.int;
        default = 45;
        description = "Compress when context is X% full.";
      };
      engineProtectFirst = lib.mkOption {
        type = lib.types.int;
        default = 2;
        description = "Messages at the start to keep verbatim.";
      };
      engineProtectLast = lib.mkOption {
        type = lib.types.int;
        default = 5;
        description = "Messages at the end to keep verbatim.";
      };
      engineMinMsgs = lib.mkOption {
        type = lib.types.int;
        default = 16;
        description = ''
          Minimum message count before compression kicks in. The
          upstream default is 8, which is too aggressive for short
          sessions — 16 prevents CCR from running on first-turn
          requests where there's nothing meaningful to compress.
        '';
      };
      toolThresholdToken = lib.mkOption {
        type = lib.types.int;
        default = 512;
        description = "Token-mode tool-result compression threshold (bytes).";
      };
      toolThresholdCache = lib.mkOption {
        type = lib.types.int;
        default = 4096;
        description = "Cache-mode tool-result compression threshold (bytes).";
      };
      terminalThreshold = lib.mkOption {
        type = lib.types.int;
        default = 1024;
        description = "Terminal-output compression threshold (bytes).";
      };
      inlineThreshold = lib.mkOption {
        type = lib.types.int;
        default = 2048;
        description = "Inline zlib fallback threshold (bytes).";
      };
      autoExpand = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Auto-expand CCR markers inline (off: stay raw).";
      };
      autoExpandLimit = lib.mkOption {
        type = lib.types.int;
        default = 0;
        description = "Auto-expand limit (0 = disabled).";
      };
      catalogMode = lib.mkOption {
        type = lib.types.enum [ "compact" "full" "tool" ];
        default = "tool";
        description = "Catalog display mode.";
      };
      classifierPoll = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Skip CCR for clean outputs.";
      };
      codeMultiplier = lib.mkOption {
        type = lib.types.float;
        default = 3.0;
        description = "Multiply threshold for code-typed content.";
      };
      contextEngine = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Mid-turn context compression engine (default on).";
      };
      prefetch = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable aphrodite_prefetch tool.";
      };
    };

    previews = {
      modelFamily = lib.mkOption {
        type = lib.types.enum [ "compact" "code_first" "balance" ];
        default = "code_first";
        description = "Preview shape family.";
      };
      codeStructureMap = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Show fn/struct/class signatures in code previews.";
      };
      previewMaxChars = lib.mkOption {
        type = lib.types.int;
        default = 120;
        description = "Max chars per preview line.";
      };
    };

    prompts = {
      retrieveGuidance = lib.mkOption {
        type = lib.types.enum [ "minimal" "standard" "verbose" ];
        default = "verbose";
        description = "How verbose the retrieve guidance prompt is.";
      };
      ccrMarkerHint = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Append '(use aphrodite_retrieve)' hint after markers.";
      };
      catalogIntentHints = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Show intent=read with hashes in catalog.";
      };
    };

    dataDir = lib.mkOption {
      type = lib.types.path;
      default = "/opt/aphrodite";
      description = ''
        WorkingDirectory for the proxy, and the parent of
        ~/.hermes/aphrodite where the CCR SQLite store lands.
        Defaults to /opt/aphrodite (created by tmpfiles.d).
        Survives reboots but is wiped by manual rm.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.runCommand "aphrodite-bin" { } ''
        mkdir -p $out/bin
        cp ${aphroditeBin} $out/bin/aphrodite
        chmod +x $out/bin/aphrodite
      '';
      description = ''
        Override the binary package (e.g. for local builds from
        source). Default fetches the upstream release binary.
      '';
    };
  };

  config = lib.mkIf autoCfg.enable {
    users.groups.aphrodite = { };
    users.users.aphrodite = {
      isSystemUser = true;
      group = "aphrodite";
    };

    # CCR SQLite store lives in services.aphrodite.dataDir.
    systemd.tmpfiles.rules = [
      "d /opt/aphrodite 0750 aphrodite aphrodite - -"
    ];

    # Loopback-only by default; only open firewall when operator
    # explicitly opts in (and only then does it make sense).
    networking.firewall.allowedTCPPorts = lib.mkIf cfg.openFirewall [
      9798
    ];

    systemd.services.aphrodite-proxy = {
      description = "Aphrodite CCR compression proxy for Hermes Agent";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      # Restart on transient failures (proxy connect refused,
      # upstream 5xx). Rate-limited so a permanent misconfig doesn't
      # churn.
      serviceConfig = {
        Type = "simple";
        User = "aphrodite";
        Group = "aphrodite";
        ExecStart = "${cfg.package}/bin/aphrodite run";
        Restart = "on-failure";
        RestartSec = "10s";

        # RuntimeDirectory creates /run/aphrodite as a writable
        # tmpfs at unit start. We drop the rendered config there
        # because /etc is read-only under NixOS; APHRODITE_CONFIG_PATH
        # below points at this writable path.
        RuntimeDirectory = "aphrodite";

        # ExecStartPre renders /run/aphrodite/aphrodite.toml with
        # the API key materialised from the sops file. Runs as
        # root (NixOS's bash wrapper around ExecStartPre) so it
        # can read the mode-0400 sops secret before the unit drops
        # to User=aphrodite. Sets -euo pipefail; non-zero exit
        # blocks start.
        ExecStartPre = preStartScript;

        # Override the proxy's default config-file search. The
        # upstream looks at ./aphrodite.toml and ~/.hermes/
        # aphrodite/aphrodite.toml in that order; we point
        # explicitly at /run/aphrodite/aphrodite.toml rendered
        # by ExecStartPre above.
        Environment = [
          "APHRODITE_CONFIG_PATH=/run/aphrodite/aphrodite.toml"
          # Pin HOME so the upstream proxy's default CCR-store
          # path (~/.hermes/aphrodite) lands under /opt/aphrodite
          # rather than the unit's stub /var/empty home (where
          # ProtectSystem=strict forbids writes).
          "HOME=/opt/aphrodite"
        ];

        # CCR SQLite store must survive restart. WorkingDirectory
        # tells the proxy where to write ccr.db (mode=token).
        WorkingDirectory = cfg.dataDir;

        # Standard process hardening. NoNewPrivileges stays on —
        # this service doesn't escalate, no need to repeat the
        # hermes-agent.service override pattern from hermes.nix.
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        ReadWritePaths = [ cfg.dataDir ];
      };

      unitConfig = {
        # Mirror openviking's pattern: rate-limit to 20 attempts
        # per 10 minutes so a permanent failure doesn't churn.
        StartLimitBurst = 20;
        StartLimitIntervalSec = 600;
      };
    };

    # When auto.aphrodite.enable goes true, enable the unit.
    systemd.services.aphrodite-proxy.enable = true;
  };
}