# OpenViking — self-hosted context database for Hermes Agent.
#
# Single NixOS module, single systemd unit (podman-openviking.service
# generated by virtualisation.oci-containers). Three responsibilities
# live as host-side hooks on that unit:
#
#   preStart     — read /run/secrets/hermes/GOOGLE_API_KEY (VLM) and
#                  optional embedding key, render
#                  /opt/openviking/conf/ov.conf,
#                  with auth_mode=api_key, root_api_key derived from
#                  Nix build-time hash of embedding config. Runs before
#                  every container start.
#
#   ExecStart    — managed by oci-containers. Pulls the image, bind-mounts
#                  /opt/openviking/conf + /opt/openviking/data, runs
#                  --network=host. Type=notify so the unit waits for the
#                  container's READY=1 before considering the start
#                  successful.
#
#   ExecStartPost — once the server is healthy, mint a user_key via
#                  the Admin API and write /opt/openviking/keys/user_key
#                  so hermes-agent can read it as EnvironmentFile.
#
# The host-side hooks are written as Nix store derivations and copied
# to stable paths under /opt/openviking/ via tmpfiles rules. systemd
# references the stable paths so a Nix rebuild that produces fresh
# store hashes doesn't break the unit.
#
# File layout on disk:
#   /opt/openviking/preStart.sh            — host-side preStart (Nix-managed)
#   /opt/openviking/execStartPost.sh       — host-side ExecStartPost (Nix-managed)
#   /opt/openviking/conf/                  — server conf dir (ov.conf)
#   /opt/openviking/data/                  — server data dir (vikingdir)
#   /opt/openviking/data/ov.conf             — server config (api_key) (legacy bind-mount)
#   /opt/openviking/keys/user_key            — user_key for hermes-agent (0640)
#
# Both data and keys are owned by `openviking:openviking`. Hermes user
# is in group `openviking` (read-only) so it can read user_key.

{ config, lib, pkgs, ... }:

let
  cfg = config.services.openviking;
  autoCfg = config.auto.openviking;

  # Root API key for OpenViking server. Generated at build time by
  # hashing the embedding provider + model + api_base, so two configs
  # that point at the same provider produce the same root key. Used
  # to mint per-user keys via the Admin API at startup. Note: this
  # is independent of any apiKeyFile path because the embedding
  # endpoint may be local (Ollama) and not need a key file at all.
  rootApiKey = "ovk_" + pkgs.lib.substring 0 32
    (builtins.hashString "sha256"
      "embedding=${cfg.embedding.provider}:${cfg.embedding.model}:${cfg.embedding.apiBase}");

  # Host-side preStart. Rendered into /opt/openviking/preStart.sh
  # via tmpfiles. Reads the embedding api-key file (if any) and the
  # vlm api-key file (if any), then writes ov.conf. Runs as root
  # before the container starts (so it can read 0400 secrets).
  preStartScript = pkgs.writeShellScript "openviking-preStart" ''
    set -euo pipefail

    # Read an api-key file. Accepts either a raw key on one line or
    # an env-file with `GOOGLE_API_KEY=` / `OPENAI_API_KEY=` lines.
    # Echoes the key on stdout; empty if KEY_SRC is empty.
    read_api_key() {
      local key_src="''${1:-}"
      local label="''${2:-api_key}"
      if [[ -z "$key_src" ]]; then
        echo ""
        return 0
      fi
      if [[ ! -f "$key_src" ]]; then
        echo "openviking: $label file not found: $key_src" >&2
        exit 1
      fi
      local key=""
      if grep -qE '^GOOGLE_API_KEY=' "$key_src"; then
        key=$(grep -E '^GOOGLE_API_KEY=' "$key_src" | head -n1 | cut -d= -f2- | tr -d '\n')
      elif grep -qE '^OPENAI_API_KEY=' "$key_src"; then
        key=$(grep -E '^OPENAI_API_KEY=' "$key_src" | head -n1 | cut -d= -f2- | tr -d '\n')
      else
        key=$(cat "$key_src" | tr -d '\n')
      fi
      if [[ -z "$key" ]]; then
        echo "openviking: empty $label in $key_src" >&2
        exit 1
      fi
      printf '%s' "$key"
    }

    EMBED_KEY_SRC=${lib.escapeShellArg (if cfg.embedding.apiKeyFile == null then "" else toString cfg.embedding.apiKeyFile)}
    VLM_KEY_SRC=${lib.escapeShellArg (if cfg.vlm.apiKeyFile == null then "" else toString cfg.vlm.apiKeyFile)}

    EMBED_KEY=$(read_api_key "$EMBED_KEY_SRC" "embedding api_key")
    VLM_KEY=$(read_api_key "$VLM_KEY_SRC" "vlm api_key")

    # Local OpenAI-compatible servers (Ollama) ignore api_key but
    # require a non-empty string. Substitute a benign placeholder.
    if [[ -z "$EMBED_KEY" ]]; then
      EMBED_KEY="ollama"
    fi
    if [[ -z "$VLM_KEY" ]]; then
      echo "openviking: vlm.apiKeyFile is null but VLM is required by the upstream server" >&2
      exit 1
    fi

    JSON=$(${pkgs.jq}/bin/jq -n \
      --arg root_key "${rootApiKey}" \
      --arg embed_key "$EMBED_KEY" \
      --arg embed_model "${cfg.embedding.model}" \
      --argjson embed_dim ${toString cfg.embedding.dimension} \
      --arg embed_base "${cfg.embedding.apiBase}" \
      --arg vlm_base "${cfg.vlm.apiBase}" \
      --arg vlm_model "${cfg.vlm.model}" \
      --arg vlm_key "$VLM_KEY" \
      '{
        server: {
          host: "127.0.0.1",
          port: ${toString cfg.port},
          auth_mode: "api_key",
          root_api_key: $root_key
        },
        storage: {
          vectordb: { name: "context", backend: "local" },
          agfs: { backend: "local" }
        },
        embedding: {
          allow_metadata_override: true,
          dense: {
            provider: "${cfg.embedding.provider}",
            api_key: $embed_key,
            api_base: $embed_base,
            model: $embed_model,
            dimension: $embed_dim
          }
        },
        vlm: {
          api_key: $vlm_key,
          api_base: $vlm_base,
          provider: "openai",
          model: $vlm_model
        }
      }')
    printf '%s' "$JSON" > ${cfg.confDir}/ov.conf
    chmod 0640 ${cfg.confDir}/ov.conf
    chown openviking:openviking ${cfg.confDir}/ov.conf
  '';

  # Host-side ExecStartPost. Rendered into /opt/openviking/execStartPost.sh
  # via tmpfiles. Mints a user_key via the Admin API after the
  # container is healthy (Type=notify waits for READY=1).
  execStartPostScript = pkgs.writeShellScript "openviking-execStartPost" ''
    set -euxo pipefail

    ENDPOINT=http://127.0.0.1:${toString cfg.port}
    KEY_FILE=${cfg.keysDir}/user_key

    # Wait for /ready to return 2xx. /health is served by the upstream
    # entrypoint's placeholder script the moment the container starts
    # — it returns {"status":"ok"} even while the real openviking-server
    # is still initialising, so any POST against /api/v1/admin/* during
    # that window gets 401 Invalid API Key. /ready is only served by
    # the real server once it has finished initialising Auth, the
    # vectordb, and the embedding circuit. Polling /ready is therefore
    # a real "the Admin API is ready" signal — when curl gets any 2xx
    # response, the real server has taken over the socket.
    for _ in $(seq 1 60); do
      code=$(${pkgs.curl}/bin/curl -s -o /dev/null -w '%{http_code}' --max-time 2 "$ENDPOINT/ready" || true)
      if [[ "$code" =~ ^2 ]]; then
        sleep 5
        break
      fi
      sleep 1
    done

    ROOT_KEY=$(${pkgs.jq}/bin/jq -r '.server.root_api_key' ${cfg.confDir}/ov.conf)

    # 1. Ensure account exists. 409 ALREADY_EXISTS is fine.
    code=$(${pkgs.curl}/bin/curl -s -o /dev/null -w '%{http_code}' -X POST \
      -H "Authorization: Bearer $ROOT_KEY" \
      -H "Content-Type: application/json" \
      -d '{"account_id":"default","admin_user_id":"default"}' \
      "$ENDPOINT/api/v1/admin/accounts")
    if [[ "$code" != "200" && "$code" != "409" ]]; then
      echo "openviking-execStartPost: account create failed: $code" >&2
      exit 1
    fi

    # 2. Mint user_key. The server auto-creates the user on first
    # boot and persists the key to
    # <dataDir>/viking/default/_system/users.json (see pitfall
    # 3c in nixos-self-edit). Try POST first (fresh installs);
    # if it returns 409 because the user already exists, fall
    # back to reading the auto-minted key from disk.
    USER_KEY=$(${pkgs.curl}/bin/curl -s -o /dev/null -w '%{http_code}' -X POST \
      -H "Authorization: Bearer $ROOT_KEY" \
      -H "Content-Type: application/json" \
      -d '{"user_id":"default","role":"user"}' \
      "$ENDPOINT/api/v1/admin/accounts/default/users" || true)
    code="$USER_KEY"

    if [[ "$code" == "200" ]]; then
      # Fresh mint: GET the key from a follow-up call.
      USER_KEY=$(${pkgs.curl}/bin/curl -fsS \
        -H "Authorization: Bearer $ROOT_KEY" \
        "$ENDPOINT/api/v1/admin/accounts/default/users/default" \
        | ${pkgs.jq}/bin/jq -r '.result.user_key // .result.key // empty')
    elif [[ "$code" == "409" ]]; then
      # User already exists; read auto-minted key from disk.
      USER_KEY=$(${pkgs.jq}/bin/jq -r '.users.default.key // empty' \
        ${cfg.dataDir}/viking/default/_system/users.json 2>/dev/null || true)
      if [[ -z "$USER_KEY" ]]; then
        echo "openviking-execStartPost: 409 on user mint and users.json has no key" >&2
        exit 1
      fi
    else
      echo "openviking-execStartPost: user mint failed: $code" >&2
      exit 1
    fi

    if [[ -z "$USER_KEY" || "$USER_KEY" == "null" ]]; then
      echo "openviking-execStartPost: empty user_key after mint-or-read" >&2
      exit 1
    fi

    # 3. Write as env-file for hermes-agent.
    printf 'OPENVIKING_API_KEY=%s\n' "$USER_KEY" > "$KEY_FILE"
    chmod 0640 "$KEY_FILE"
  '';
in
{
  options.services.openviking = {
    enable = lib.mkEnableOption "OpenViking self-hosted context database for Hermes Agent";

    image = lib.mkOption {
      type = lib.types.str;
      default = "ghcr.io/volcengine/openviking:v0.4.12";
      description = "Container image to run.";
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = 1933;
      description = "Port for openviking-server to listen on.";
    };

    confDir = lib.mkOption {
      type = lib.types.path;
      default = "/opt/openviking/conf";
      description = ''
        Directory for the read-only server config (ov.conf). Bind-mounted
        into the container at /app/.openviking, which is the default
        OPENVIKING_CONFIG_FILE path inside the upstream image.
      '';
    };

    dataDir = lib.mkOption {
      type = lib.types.path;
      default = "/opt/openviking/data";
      description = ''
        Server runtime data directory. Bind-mounted into the container at
        /app/data, which is where openviking v0.4.12 actually writes its
        accounts, users, vectordb, and viking/ state. Despite upstream
        docs saying everything lives under /app/.openviking, the
        server has its own /app/data default workspace.
      '';
    };

    keysDir = lib.mkOption {
      type = lib.types.path;
      default = "/opt/openviking/keys";
      description = "Directory for the user_key file (mode 0750 openviking:openviking).";
    };

    # Embedding config. Defaults point at a local Ollama server
    # (OpenAI-compatible API on 127.0.0.1:11434) running
    # nomic-embed-text:v1.5 (84 MB Q4_K_M, 768-dim). To switch back
    # to Gemini cloud embedding, override embedding.provider,
    # embedding.model, embedding.apiBase, and provide an apiKeyFile.
    embedding = {
      provider = lib.mkOption {
        type = lib.types.str;
        default = "openai";
        description = "Embedding provider name as expected by upstream (gemini | openai).";
      };
      model = lib.mkOption {
        type = lib.types.str;
        # Default to the HF-tagged Q4_K_M GGUF. Ollama's own
        # registry only ships F16 for this model (~262 MB), but
        # the upstream nomic-ai GGUF repo exposes Q4_K_M (84 MB,
        # ~95% retrieval quality, ~3x cheaper on CPU/RAM). The
        # hf.co/... pull URL works with `ollama pull` directly
        # without a custom Modelfile.
        default = "hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:Q4_K_M";
        description = "Embedding model identifier. Must match the dimension. Use the Ollama-resolvable name (works for both registry tags like 'nomic-embed-text:v1.5' and direct HuggingFace tags like 'hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:Q4_K_M').";
      };
      dimension = lib.mkOption {
        type = lib.types.int;
        default = 768;
        description = "Embedding output dimension. Vectordb is keyed on this — switching models requires wiping /opt/openviking/data/viking/.";
      };
      apiBase = lib.mkOption {
        type = lib.types.str;
        default = "http://127.0.0.1:11434/v1";
        description = "OpenAI-compatible endpoint URL. Local Ollama by default.";
      };
      apiKeyFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        # null when the provider doesn't need a key (Ollama ignores
        # it). Required for cloud providers (gemini, openai).
        default = null;
        description = ''
          Path to the embedding API key. Required for cloud providers
          (gemini, openai); leave null for local OpenAI-compatible
          servers like Ollama that ignore the key.
        '';
      };
    };

    # VLM config. Always routes through Google via the host proxy
    # because the upstream openviking-server requires a real chat
    # model and we don't host one locally.
    vlm = {
      apiBase = lib.mkOption {
        type = lib.types.str;
        default = "https://generativelanguage.googleapis.com/v1beta/openai/";
        description = "OpenAI-compatible VLM endpoint.";
      };
      model = lib.mkOption {
        type = lib.types.str;
        default = "gemini-2.0-flash";
        description = "VLM model identifier.";
      };
      apiKeyFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = "/run/secrets/hermes/GOOGLE_API_KEY";
        description = ''
          Path to the VLM API key. Required for cloud VLM; set null to
          disable VLM (upstream server may refuse to start without one).
        '';
      };
    };

    proxyUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "http://127.0.0.1:7890";
      description = "HTTP proxy for the VLM endpoint (cloud providers). Set null to disable. Has no effect on local embedding providers.";
    };
  };

  config = lib.mkIf autoCfg.enable {

    # OpenViking system user + group. NixOS auto-assigns an unused
    # uid for isSystemUser=true. Hermes user gets read-only group
    # access so it can read /opt/openviking/keys/user_key.
    users.groups.openviking = { };
    users.users.openviking = {
      isSystemUser = true;
      group = "openviking";
    };
    # (users.users.hermes.extraGroups = [ "openviking" ] moved to hermes/default.nix)

    # Persistent dirs + host-side hook scripts. tmpfiles rules
    # land the scripts on every boot so the unit's stable paths
    # resolve to fresh Nix-rendered content.
    systemd.tmpfiles.rules = [
      "d /opt/openviking 0750 openviking openviking - -"
      "d /opt/openviking/conf 0750 openviking openviking - -"
      "d /opt/openviking/data 0750 openviking openviking - -"
      "d /opt/openviking/keys 0750 openviking openviking - -"
      "L+ /opt/openviking/preStart.sh - - - - ${preStartScript}"
      "L+ /opt/openviking/execStartPost.sh - - - - ${execStartPostScript}"
    ];

    # The container. virtualisation.oci-containers.containers
    # generates podman-openviking.service (or docker-openviking
    # depending on backend) that owns the container lifecycle.
    # Host-side hooks attached via systemd.services."podman-openviking"
    # below reference the stable /opt/openviking/*.sh paths.
    virtualisation.oci-containers.containers.openviking = {
      image = cfg.image;
      extraOptions = [ "--network=host" ];
      volumes = [
        "${cfg.confDir}:/app/.openviking"
        "${cfg.dataDir}:/app/data"
      ];
      environment = {
        OPENVIKING_SERVER_HOST = "127.0.0.1";
        OPENVIKING_SERVER_PORT = toString cfg.port;
        OPENVIKING_WITH_BOT = "0";
      } // lib.optionalAttrs (cfg.proxyUrl != null) {
        HTTP_PROXY = cfg.proxyUrl;
        HTTPS_PROXY = cfg.proxyUrl;
        ALL_PROXY = cfg.proxyUrl;
        # NO_PROXY includes 127.0.0.1 so the local Ollama endpoint
        # bypasses the proxy — Ollama is reachable directly via the
        # shared host network namespace.
        NO_PROXY = "127.0.0.1,localhost,::1";
      };
    };

    # Host-side hooks on the container service. Restart=on-failure
    # so transient failures (a proxy hiccup, a temporary 401 from
    # the Admin API) self-heal on the next try. Rate-limited to 20
    # attempts per 10 minutes so a permanent failure doesn't churn
    # through retries.
    systemd.services."podman-openviking" = {
      serviceConfig = {
        Restart = "on-failure";
        RestartSec = "30s";
        # Override the upstream oci-containers-generated ExecStartPost.
        # When set via systemd.services.X.postStart = "-/path", NixOS
        # loses the '-' prefix because it wraps the script in a bash
        # helper that has set -e. Putting ExecStartPost directly in
        # serviceConfig (with mkForce to override upstream) lets systemd
        # honour the prefix.
        ExecStartPost = lib.mkForce "-/opt/openviking/execStartPost.sh";
      };
      preStart = "/opt/openviking/preStart.sh";
      startLimitBurst = 20;
      startLimitIntervalSec = 600;
    };
  };
}
