# OpenViking — self-hosted context database for Hermes Agent.
#
# Container service (podman-openviking.service, generated by
# virtualisation.oci-containers) with two host-side hooks:
#
#   preStart         — renders /opt/openviking/conf/ov.conf, but only
#                      when missing, so manual edits aren't clobbered.
#                      Reads api-key files (embedding + VLM) and
#                      bakes rootApiKey into the server config.
#
#   ExecStartPost    — after the server reports /ready, mints a
#                      user_key via the Admin API and writes it to
#                      /opt/openviking/keys/user_key for hermes-agent.
#
# Hook scripts live as Nix store derivations; tmpfiles symlinks them
# to /opt/openviking/{pre,post}-start.sh so the unit's stable paths
# keep resolving across rebuilds.

{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.openviking;
  autoCfg = config.auto.openviking;

  preStartScript = pkgs.writeShellScript "openviking-pre-start" ''
    set -euo pipefail

    CONF=${cfg.confDir}/ov.conf
    echo "openviking-pre-start: starting (conf=$CONF, port=${toString cfg.port})"

    # Idempotent: skip render if ov.conf exists. To force re-render,
    # delete the file and restart the unit.
    if [[ -f "$CONF" ]]; then
      echo "openviking-pre-start: ov.conf already exists, skipping render"
      exit 0
    fi

    # Reads a bare api-key (single line, no KEY= prefix). Empty if
    # KEY_SRC is empty.
    read_api_key() {
      local key_src="''${1:-}"
      local label="''${2:-api_key}"
      if [[ -z "$key_src" ]]; then
        echo ""
        return 0
      fi
      if [[ ! -f "$key_src" ]]; then
        echo "openviking-pre-start: $label file not found: $key_src" >&2
        exit 1
      fi
      local key
      key=$(tr -d '\n' < "$key_src")
      if [[ -z "$key" ]]; then
        echo "openviking-pre-start: empty $label in $key_src" >&2
        exit 1
      fi
      printf '%s' "$key"
    }

    EMBED_KEY_SRC=${
      lib.escapeShellArg (
        if cfg.embedding.apiKeyFile == null then "" else toString cfg.embedding.apiKeyFile
      )
    }
    VLM_KEY_SRC=${
      lib.escapeShellArg (if cfg.vlm.apiKeyFile == null then "" else toString cfg.vlm.apiKeyFile)
    }

    EMBED_KEY=$(read_api_key "$EMBED_KEY_SRC" "embedding api_key")
    VLM_KEY=$(read_api_key "$VLM_KEY_SRC" "vlm api_key")

    # Local OpenAI-compatible servers (Ollama) ignore api_key but
    # require a non-empty string.
    if [[ -z "$EMBED_KEY" ]]; then
      EMBED_KEY="ollama"
    fi
    if [[ -z "$VLM_KEY" ]]; then
      echo "openviking-pre-start: vlm.apiKeyFile is null but VLM is required by the upstream server" >&2
      exit 1
    fi

    JSON=$(${pkgs.jq}/bin/jq -n \
      --arg root_key ${lib.escapeShellArg cfg.rootApiKey} \
      --arg embed_key "$EMBED_KEY" \
      --arg embed_model "${cfg.embedding.model}" \
      --argjson embed_dim ${toString cfg.embedding.dimension} \
      --arg embed_base "${cfg.embedding.apiBase}" \
      --arg vlm_base "${cfg.vlm.apiBase}" \
      --arg vlm_model "${cfg.vlm.model}" \
      --arg vlm_key "$VLM_KEY" \
      '{
        server: {
          host: "127.0.0.1",
          port: ${toString cfg.port},
          auth_mode: "api_key",
          root_api_key: $root_key
        },
        storage: {
          vectordb: { name: "context", backend: "local" },
          agfs: { backend: "local" }
        },
        embedding: {
          allow_metadata_override: true,
          dense: {
            provider: "${cfg.embedding.provider}",
            api_key: $embed_key,
            api_base: $embed_base,
            model: $embed_model,
            dimension: $embed_dim
          }
        },
        vlm: {
          api_key: $vlm_key,
          api_base: $vlm_base,
          provider: "openai",
          model: $vlm_model
        }
      }')
    printf '%s' "$JSON" > "$CONF"
    chmod 0640 "$CONF"
    chown openviking:openviking "$CONF"
    echo "openviking-pre-start: wrote $CONF"
  '';

  execStartPostScript = pkgs.writeShellScript "openviking-post-start" ''
    set -euo pipefail

    ENDPOINT=http://127.0.0.1:${toString cfg.port}
    KEY_FILE=${cfg.keysDir}/user_key
    ROOTAPI_KEY=${lib.escapeShellArg cfg.rootApiKey}

    # Wait for /ready. /health is served by the upstream entrypoint's
    # placeholder the moment the container starts and returns 200
    # while the real server is still initialising, so POSTs against
    # /api/v1/admin/* during that window get 401. /ready is only
    # served by the real server once auth + vectordb + embedding
    # circuit are up — a 2xx means the Admin API is actually usable.
    for _ in $(seq 1 60); do
      code=$(${pkgs.curl}/bin/curl -s -o /dev/null -w '%{http_code}' --max-time 2 "$ENDPOINT/ready" || true)
      if [[ "$code" =~ ^2 ]]; then
        sleep 5
        break
      fi
      sleep 1
    done

    # Ensure default account exists. 409 ALREADY_EXISTS is fine.
    code=$(${pkgs.curl}/bin/curl -s -o /dev/null -w '%{http_code}' -X POST \
      -H "Authorization: Bearer $ROOTAPI_KEY" \
      -H "Content-Type: application/json" \
      -d '{"account_id":"default","admin_user_id":"default"}' \
      "$ENDPOINT/api/v1/admin/accounts")
    if [[ "$code" != "200" && "$code" != "409" ]]; then
      echo "openviking-post-start: account create failed: $code" >&2
      exit 1
    fi

    # Mint user_key. The server auto-creates the default user on first
    # boot and persists the key to
    # <dataDir>/viking/default/_system/users.json. POST succeeds with
    # 200 on a fresh install; 409 means the user exists and we have
    # to read the key from disk.
    POST_BODY=$(mktemp)
    code=$(${pkgs.curl}/bin/curl -sS -o "$POST_BODY" -w '%{http_code}' -X POST \
      -H "Authorization: Bearer $ROOTAPI_KEY" \
      -H "Content-Type: application/json" \
      -d '{"user_id":"default","role":"user"}' \
      "$ENDPOINT/api/v1/admin/accounts/default/users" || true)

    if [[ "$code" == "200" ]]; then
      USER_KEY=$(${pkgs.jq}/bin/jq -r '.result.user_key // .user_key // empty' < "$POST_BODY")
      rm -f "$POST_BODY"
      if [[ -z "$USER_KEY" ]]; then
        USER_KEY=$(${pkgs.jq}/bin/jq -r '.users.default.key // empty' \
          ${cfg.dataDir}/viking/default/_system/users.json 2>/dev/null || true)
      fi
    elif [[ "$code" == "409" ]]; then
      rm -f "$POST_BODY"
      USER_KEY=$(${pkgs.jq}/bin/jq -r '.users.default.key // empty' \
        ${cfg.dataDir}/viking/default/_system/users.json 2>/dev/null || true)
      if [[ -z "$USER_KEY" ]]; then
        echo "openviking-post-start: 409 on user mint and users.json has no key" >&2
        exit 1
      fi
    else
      rm -f "$POST_BODY"
      echo "openviking-post-start: user mint failed: $code" >&2
      exit 1
    fi

    if [[ -z "$USER_KEY" || "$USER_KEY" == "null" ]]; then
      echo "openviking-post-start: empty user_key after mint-or-read" >&2
      exit 1
    fi

    printf 'OPENVIKING_API_KEY=%s\n' "$USER_KEY" > "$KEY_FILE"
    chmod 0640 "$KEY_FILE"
  '';
in
{
  options.services.openviking = {
    enable = lib.mkEnableOption "OpenViking self-hosted context database for Hermes Agent";

    rootApiKey = lib.mkOption {
      type = lib.types.str;
      example = "ovk_root_aleroza_pc_001";
      description = ''
        Root API key for auth_mode=api_key on the Admin API. Must be
        supplied as a module argument — the module does not derive it,
        so the value is stable across reconfigures regardless of which
        embedding provider or model is configured. Local-only; never
        sent off-host.
      '';
    };

    image = lib.mkOption {
      type = lib.types.str;
      default = "ghcr.io/volcengine/openviking:v0.4.12";
      description = "Container image to run.";
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = 1933;
      description = "Port for openviking-server to listen on.";
    };

    confDir = lib.mkOption {
      type = lib.types.path;
      default = "/opt/openviking/conf";
      description = ''
        Server config directory, bind-mounted to /app/.openviking
        (the default OPENVIKING_CONFIG_FILE path inside the image).
      '';
    };

    dataDir = lib.mkOption {
      type = lib.types.path;
      default = "/opt/openviking/data";
      description = ''
        Server runtime data directory, bind-mounted to /app/data
        where openviking v0.4.12 writes accounts, users, vectordb,
        and viking/ state. Despite upstream docs saying everything
        lives under /app/.openviking, the server has its own
        /app/data default workspace.
      '';
    };

    keysDir = lib.mkOption {
      type = lib.types.path;
      default = "/opt/openviking/keys";
      description = "Directory for the user_key file (mode 0750 openviking:openviking).";
    };

    embedding = {
      provider = lib.mkOption {
        type = lib.types.str;
        default = "openai";
        description = "Embedding provider name as expected by upstream (gemini | openai).";
      };
      model = lib.mkOption {
        type = lib.types.str;
        # Q4_K_M GGUF pulled directly from HuggingFace — Ollama's
        # registry only ships F16 (~262 MB), Q4_K_M is ~84 MB and
        # retains ~95% retrieval quality.
        default = "hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:Q4_K_M";
        description = "Embedding model identifier. Must match the dimension. Accepts Ollama-resolvable names (registry tags or hf.co/... GGUF tags).";
      };
      dimension = lib.mkOption {
        type = lib.types.int;
        default = 768;
        description = "Embedding output dimension. Vectordb is keyed on this — switching models requires wiping /opt/openviking/data/viking/.";
      };
      apiBase = lib.mkOption {
        type = lib.types.str;
        default = "http://127.0.0.1:11434/v1";
        description = "OpenAI-compatible endpoint URL. Local Ollama by default.";
      };
      apiKeyFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = ''
          Path to a file containing a bare embedding API key (single
          line, no KEY= prefix). Required for cloud providers; leave
          null for local OpenAI-compatible servers like Ollama that
          ignore the key.
        '';
      };
    };

    vlm = {
      apiBase = lib.mkOption {
        type = lib.types.str;
        default = "https://generativelanguage.googleapis.com/v1beta/openai/";
        description = "OpenAI-compatible VLM endpoint.";
      };
      model = lib.mkOption {
        type = lib.types.str;
        default = "gemini-2.0-flash";
        description = "VLM model identifier.";
      };
      apiKeyFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = "/run/secrets/hermes/GOOGLE_API_KEY";
        description = ''
          Path to a file containing a bare VLM API key (single line,
          no KEY= prefix). Required for cloud VLM; set null to disable
          VLM (upstream server may refuse to start without one).
        '';
      };
    };

    proxyUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "http://127.0.0.1:7890";
      description = "HTTP proxy for the VLM endpoint. Set null to disable. Has no effect on local embedding providers.";
    };
  };

  config = lib.mkIf autoCfg.enable {

    users.groups.openviking = { };
    users.users.openviking = {
      isSystemUser = true;
      group = "openviking";
    };

    systemd.tmpfiles.rules = [
      "d /opt/openviking 0750 openviking openviking - -"
      "d /opt/openviking/conf 0750 openviking openviking - -"
      "d /opt/openviking/data 0750 openviking openviking - -"
      "d /opt/openviking/keys 0750 openviking openviking - -"
      "L+ /opt/openviking/pre-start.sh - - - - ${preStartScript}"
      "L+ /opt/openviking/post-start.sh - - - - ${execStartPostScript}"
    ];

    virtualisation.oci-containers.containers.openviking = {
      image = cfg.image;
      extraOptions = [ "--network=host" ];
      volumes = [
        "${cfg.confDir}:/app/.openviking"
        "${cfg.dataDir}:/app/data"
      ];
      environment = {
        OPENVIKING_SERVER_HOST = "127.0.0.1";
        OPENVIKING_SERVER_PORT = toString cfg.port;
        OPENVIKING_WITH_BOT = "0";
      }
      // lib.optionalAttrs (cfg.proxyUrl != null) {
        HTTP_PROXY = cfg.proxyUrl;
        HTTPS_PROXY = cfg.proxyUrl;
        ALL_PROXY = cfg.proxyUrl;
        # NO_PROXY keeps the local Ollama endpoint off the proxy —
        # reachable directly via the shared host network namespace.
        NO_PROXY = "127.0.0.1,localhost,::1";
      };
    };

    # Restart=on-failure so transient failures (proxy hiccup, 401
    # during Admin API init) self-heal. Rate-limited to 20 attempts
    # per 10 minutes so a permanent failure doesn't churn.
    systemd.services."podman-openviking" = {
      serviceConfig = {
        Restart = "on-failure";
        RestartSec = "30s";
        # Override the upstream oci-containers-generated ExecStartPost.
        # systemd.services.X.postStart = "-/path" loses the '-' prefix
        # because NixOS wraps it in a bash helper with set -e; setting
        # ExecStartPost directly with mkForce keeps the prefix.
        ExecStartPost = lib.mkForce "-/opt/openviking/post-start.sh";
      };
      preStart = "/opt/openviking/pre-start.sh";
      startLimitBurst = 20;
      startLimitIntervalSec = 600;
    };
  };
}